twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    #la liste des templates de formulaires est dispo ici : vendor/Symfony/twig-bridge/Resources/views/Form
    form_themes: ['bootstrap_4_layout.html.twig']
